name: Release with filt

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    uses: ./.github/workflows/build.yml

  create-release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        id: download
        with:
          name: build-artifact
      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.download.outputs.download-path }}/*.whl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
